package transfer

import (
	"fmt"
	"io"
	"net"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/pkg/sftp"
	"golang.org/x/crypto/ssh"
)

// Client wraps an SSH connection. Bulk data transfers use raw SSH exec sessions
// (cat / cat >) for SCP-like throughput. The embedded SFTP sub-client is used
// only for metadata operations (mkdir, remove).
type Client struct {
	sshConn *ssh.Client
	sftp    *sftp.Client
}

// NewClient creates a new client using SSH key or password authentication.
func NewClient(host string, port int, user, keyPath, password string) (*Client, error) {
	var authMethods []ssh.AuthMethod

	if keyPath != "" {
		key, err := os.ReadFile(keyPath)
		if err != nil {
			return nil, fmt.Errorf("read ssh key: %w", err)
		}
		signer, err := ssh.ParsePrivateKey(key)
		if err != nil {
			return nil, fmt.Errorf("parse ssh key: %w", err)
		}
		authMethods = append(authMethods, ssh.PublicKeys(signer))
	}

	if password != "" {
		authMethods = append(authMethods, ssh.Password(password))
	}

	if len(authMethods) == 0 {
		return nil, fmt.Errorf("no SSH authentication method configured (set remote_key_path or remote_password)")
	}

	sshCfg := &ssh.ClientConfig{
		User: user,
		Auth: authMethods,
		// Accept any host key. For production, replace with a known_hosts-based callback.
		HostKeyCallback: ssh.InsecureIgnoreHostKey(), //nolint:gosec
		Timeout:         30 * time.Second,
	}

	addr := net.JoinHostPort(host, fmt.Sprintf("%d", port))
	conn, err := ssh.Dial("tcp", addr, sshCfg)
	if err != nil {
		return nil, fmt.Errorf("ssh dial %s: %w", addr, err)
	}

	sftpClient, err := sftp.NewClient(conn)
	if err != nil {
		conn.Close()
		return nil, fmt.Errorf("sftp new client: %w", err)
	}

	return &Client{sshConn: conn, sftp: sftpClient}, nil
}

// Close closes the SFTP sub-client and the underlying SSH connection.
func (c *Client) Close() error {
	if err := c.sftp.Close(); err != nil {
		return err
	}
	return c.sshConn.Close()
}

// blobShard returns the one-character shard directory for a blob ID.
// Blob IDs are random UUIDs (e.g. from uuid.New().String()), so the first
// hex digit (0-9, a-f) distributes blobs evenly across 16 subdirectories.
// blobID must be non-empty (UUIDs generated by the agent always satisfy this).
func blobShard(blobID string) string {
	if len(blobID) == 0 {
		panic("blobShard: blobID must not be empty")
	}
	return blobID[:1]
}

// shellQuote returns a single-quoted string that is safe to embed in a POSIX
// shell command. It handles embedded single-quotes by ending the single-quoted
// segment, inserting an escaped quote, and reopening the single-quoted segment.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// validateBlobID returns an error if blobID is not in the expected UUID format
// (32 hex digits and 4 hyphens). This is a defence-in-depth check to ensure
// that blob IDs used in shell commands contain only safe characters, regardless
// of how the ID was generated.
func validateBlobID(blobID string) error {
	for _, r := range blobID {
		if !((r >= '0' && r <= '9') || (r >= 'a' && r <= 'f') || (r >= 'A' && r <= 'F') || r == '-') {
			return fmt.Errorf("invalid blob ID character %q in %q", r, blobID)
		}
	}
	return nil
}

// UploadBlob streams data from r to remotePath/<shard>/blobID using an SSH
// exec session running "cat >" on the remote side. This bypasses SFTP packet
// overhead and achieves throughput comparable to SCP.
// The shard subdirectory is created via SFTP (a cheap metadata operation).
func (c *Client) UploadBlob(remotePath, blobID string, r io.Reader) error {
	if err := validateBlobID(blobID); err != nil {
		return err
	}
	shardDir := filepath.Join(remotePath, blobShard(blobID))
	if err := c.sftp.MkdirAll(shardDir); err != nil {
		return fmt.Errorf("sftp mkdir %s: %w", shardDir, err)
	}
	dest := filepath.Join(shardDir, blobID)

	sess, err := c.sshConn.NewSession()
	if err != nil {
		return fmt.Errorf("ssh new session: %w", err)
	}
	defer sess.Close()

	stdin, err := sess.StdinPipe()
	if err != nil {
		return fmt.Errorf("ssh stdin pipe: %w", err)
	}

	if err := sess.Start("cat > " + shellQuote(dest)); err != nil {
		stdin.Close()
		return fmt.Errorf("ssh exec: %w", err)
	}

	_, copyErr := io.Copy(stdin, r)
	closeErr := stdin.Close()
	waitErr := sess.Wait()

	if copyErr != nil {
		return fmt.Errorf("stream upload %s: %w", dest, copyErr)
	}
	if closeErr != nil {
		return fmt.Errorf("close stdin: %w", closeErr)
	}
	if waitErr != nil {
		return fmt.Errorf("ssh exec wait: %w", waitErr)
	}
	return nil
}

// DeleteBlob removes a remote blob by ID from its shard subdirectory.
func (c *Client) DeleteBlob(remotePath, blobID string) error {
	dest := filepath.Join(remotePath, blobShard(blobID), blobID)
	return c.sftp.Remove(dest)
}

// sshReadCloser wraps an SSH session's stdout so the caller can stream the
// remote command output and close the session when done (or on error).
type sshReadCloser struct {
	io.Reader
	sess *ssh.Session
}

// Close terminates the SSH session. Safe to call whether the remote command
// has already exited or if the caller stopped reading early.
func (r *sshReadCloser) Close() error {
	return r.sess.Close()
}

// DownloadBlob opens a streaming SSH exec session running "cat" on the remote
// blob file and returns the session's stdout as an io.ReadCloser. This bypasses
// SFTP packet overhead for bulk data, matching SCP-level throughput.
func (c *Client) DownloadBlob(remotePath, blobID string) (io.ReadCloser, error) {
	if err := validateBlobID(blobID); err != nil {
		return nil, err
	}
	src := filepath.Join(remotePath, blobShard(blobID), blobID)

	sess, err := c.sshConn.NewSession()
	if err != nil {
		return nil, fmt.Errorf("ssh new session: %w", err)
	}

	stdout, err := sess.StdoutPipe()
	if err != nil {
		sess.Close()
		return nil, fmt.Errorf("ssh stdout pipe: %w", err)
	}

	if err := sess.Start("cat " + shellQuote(src)); err != nil {
		sess.Close()
		return nil, fmt.Errorf("ssh exec: %w", err)
	}

	return &sshReadCloser{Reader: stdout, sess: sess}, nil
}

// EnsureDir creates remote directories recursively if they don't exist.
func (c *Client) EnsureDir(path string) error {
	return c.sftp.MkdirAll(path)
}
